### PR TITLE
dts/: Implement enter as the default answer (capital letter)

### PR DESCRIPTION
**Pull request by EduKav1813**

### CODE REVIEW

**Comment by artur-rs** [comment]
@EduKav1813, is it ready for review if it's a draft?

**Comment by EduKav1813** [comment]
I found a few points that I missed, so I need to update this PR and then it would be ready for review

**Comment by EduKav1813** [comment]
Should be ready now

**Comment by EduKav1813** [comment]
I will rebase this on develop (forgot about that and used main)

**Pull request closed without merging**
