### PR TITLE
Fix issue 957

### PR DESCRIPTION
**Pull request by DaniilKl**
This commit fixes issue https://github.com/Dasharo/dasharo-issues/issues/957.

### CODE REVIEW

**Comment by PLangowski** [comment]
@DaniilKl Which commits from this PR fix the issue?

**Comment by DaniilKl** [comment]
None of the commits. This is an old PR. Closed to avoid confusion.

**Comment by PLangowski** [comment]
ok, was it fixed in another PR then?

**Comment by m-iwanicki** [comment]
I don't think there was any progress on this issue

**Pull request closed without merging**
