### PR TITLE
dts: initial deployment for PC Engines SeaBIOS

### PR DESCRIPTION
**Pull request by macpijan**
Flow:

```
  DTS version v1.2.21

  1) Dasharo HCL report - dump hardware information from this device
  2) Install Dasharo firmware
  4) Edit your DES keys
     Logs key    :  27a8jYbDXFk9c7T
     Download key:  y4MjqNXXQKFJHXZ
     Password    :  DnuZx)5x&<Jz
  8) Stop SSH server
  9) Shell
  10) Power off system
  11) Reboot system

Enter an option: 2

Waiting for network connection ...
Preparing ...
Waiting for network connection ...
Checking if board is Dasharo compatible.
Gathering flash chip and chipset information...
Flash information: Mock flashrom: Extra options = --flash-name 
/usr/sbin/dts-functions.sh: line 668: Mock flashrom: Extra options = --flash-size  / 1024 / 1024: syntax error in expression (error token is "flashrom: Extra options = --flash-size  / 1024 / 1024")
Backing up BIOS firmware and store it locally...
Remember that firmware is also backed up in HCL report.
Saving backup to: /fw_backup.tar.gz
tar: Removing leading `/' from member names
Successfully backed up firmware locally at: /fw_backup.tar.gz

Please, select Dasharo firmware version to install
  d) DES version (coreboot + UEFI)
  s) DES version (coreboot + SeaBIOS)
  b) Back to main menu

Enter an option: s

Dasharo Entry Subscription (coreboot + SeaBIOS) version selected
Downloading Dasharo firmware...Done

Please verify detected hardware!

Board vendor: PC Engines
System model: APU2
Board model: APU2

Does it match your actual specification? (Y|n) y

Following firmware will be used to install Dasharo
Dasharo BIOS firmware:
  - link: https://cloud.3mdeb.com/public.php/webdav/pcengines_apu2/v24.05.00.01/pcengines_apu2_seabios_v24.05.00.01.rom
  - hash: d58ca8e6282699f02ae665c1d9c8f755ad2417005d6a55031f3337dce00292a8

You can learn more about this release on: https://docs.dasharo.com/

Do you want to install Dasharo firmware on your hardware? (Y|n) y

Checking Dasharo firmware checksum... Verified.

Found file config at 0x1a640, type raw, compressed 3107, size 9925
Installing Dasharo firmware...
Successfully installed Dasharo firmware
Syncing disks... Done.
The computer will reboot automatically in 5 seconds
Rebooting in 5s:
5...
4...
3...
2...
```

### CODE REVIEW

**Comment by pietrushnic** [comment]
I also have issues with building DTS. I had lshw branch built, so at least some sstate, downloads, and other stuff should be helpful, but after switching branches kas reported the following issue:

```bash
[2:24:11] pietrushnic:dasharo $ SHELL=/bin/bash kas-container build meta-dts/kas.yml
2024-06-27 00:24:15 - INFO     - kas 3.0.2 started
2024-06-27 00:24:15 - INFO     - /repo$ git rev-parse --show-toplevel
2024-06-27 00:24:15 - INFO     - /repo$ git rev-parse --show-toplevel
2024-06-27 00:24:15 - INFO     - /repo$ git rev-parse --show-toplevel                                                                                                                          2024-06-27 00:24:15 - INFO     - Using /repo as root for repository meta-dts
2024-06-27 00:24:15 - INFO     - /work/poky$ git remote set-url origin https://git.yoctoproject.org/git/poky
2024-06-27 00:24:15 - INFO     - /work/meta-openembedded$ git remote set-url origin https://git.openembedded.org/meta-openembedded
2024-06-27 00:24:15 - INFO     - /work/meta-security$ git remote set-url origin https://git.yoctoproject.org/git/meta-security
2024-06-27 00:24:15 - INFO     - /work/poky$ git cat-file -t 00c04394cbc5ecaced7cc1bc8bc8787e621f987d
2024-06-27 00:24:15 - INFO     - /work/meta-openembedded$ git cat-file -t 0b78362654262145415df8211052442823b9ec9b
2024-06-27 00:24:15 - INFO     - /work/meta-security$ git cat-file -t c79262a30bd385f5dbb009ef8704a1a01644528e
2024-06-27 00:24:15 - INFO     - Repository poky already contains 00c04394cbc5ecaced7cc1bc8bc8787e621f987d as commit
2024-06-27 00:24:15 - INFO     - Repository meta-openembedded already contains 0b78362654262145415df8211052442823b9ec9b as commit
2024-06-27 00:24:15 - INFO     - Repository meta-security already contains c79262a30bd385f5dbb009ef8704a1a01644528e as commit
2024-06-27 00:24:15 - INFO     - /repo$ git rev-parse --show-toplevel
2024-06-27 00:24:15 - INFO     - Using /repo as root for repository meta-dts
2024-06-27 00:24:15 - INFO     - /work/poky$ git status -s
2024-06-27 00:24:15 - INFO     - /work/poky$ git rev-parse --verify -q origin/00c04394cbc5ecaced7cc1bc8bc8787e621f987d
2024-06-27 00:24:15 - INFO     - /work/poky$ git checkout -q 00c04394cbc5ecaced7cc1bc8bc8787e621f987d
2024-06-27 00:24:15 - INFO     - /work/meta-openembedded$ git status -s
2024-06-27 00:24:15 - INFO     - /work/meta-openembedded$ git rev-parse --verify -q origin/0b78362654262145415df8211052442823b9ec9b
2024-06-27 00:24:15 - INFO     - /work/meta-openembedded$ git checkout -q 0b78362654262145415df8211052442823b9ec9b
2024-06-27 00:24:15 - INFO     - /work/meta-security$ git status -s
2024-06-27 00:24:15 - INFO     - /work/meta-security$ git rev-parse --verify -q origin/c79262a30bd385f5dbb009ef8704a1a01644528e
2024-06-27 00:24:15 - INFO     - /work/meta-security$ git checkout -q c79262a30bd385f5dbb009ef8704a1a01644528e
2024-06-27 00:24:15 - INFO     - /repo$ git rev-parse --show-toplevel
2024-06-27 00:24:15 - INFO     - Using /repo as root for repository meta-dts
2024-06-27 00:24:15 - INFO     - /repo$ git rev-parse --show-toplevel
2024-06-27 00:24:15 - INFO     - Using /repo as root for repository meta-dts
2024-06-27 00:24:15 - INFO     - /work/poky$ /tmp/tmpjh7w_tj2/get_bb_env /build
2024-06-27 00:24:15 - ERROR    - Command "/work/poky$ /tmp/tmpjh7w_tj2/get_bb_env /build" failed
--- Error summary ---
Error: TEMPLATECONF value points to nonexistent directory 'meta-poky/conf/templates/default'
```

I could not remove it until I removed the build directory (even cleanall didn't help). Maybe there is a better way to deal with such issues, but I didn't find it.

I'm in the process of building this code now, but I already see errors:

```bash
WARNING: ifdtool-git-r0 do_fetch: Failed to fetch URL git://github.com/Dasharo/coreboot.git;protocol=https;branch=dasharo, attempting MIRRORS if available
ERROR: ifdtool-git-r0 do_fetch: Fetcher failure: Unable to find revision d08d5eaa98b1204b5e665d3ae4f63fb6f84a0d77 in branch dasharo even from upstream
ERROR: ifdtool-git-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/Dasharo/coreboot.git;protocol=https;branch=dasharo')
ERROR: Logfile of failure stored in: /build/tmp/work/core2-64-dts-linux/ifdtool/git-r0/temp/log.do_fetch.878
ERROR: Task (/repo/meta-dts-distro/recipes-bsp/coreboot-utils/ifdtool_git.bb:do_fetch) failed with exit code '1'
```

**Comment by macpijan** [comment]
> I could not remove it until I removed the build directory (even cleanall didn't help). Maybe there is a better way to deal with such issues, but I didn't find it.

There are 2 very different yocto versions on these branches right now, so using separate build directories works best here.

> I'm in the process of building this code now, but I already see errors:

I see that Daharo coreboot rebase breaking our builds, if we rebase the main branch :( 

We could build from develop, but I am more afraid of releasing it **right now** as we have not tested it much yet, and we have much more changes there.

**Comment by macpijan** [comment]
With b4cef84fa7c682c9b54746d2af48c1b6c4664bbb it builds fine for me

**Comment by pietrushnic** [comment]
@macpijan, I added some commits for which I need to pass PC Engines tests. I will test other features introduced in this MR next.

**Pull request closed without merging**
