### PR TITLE
Set trust level for GPG master keys

### PR DESCRIPTION
**Pull request by miczyg1**

### CODE REVIEW

**Comment by mkopec** [comment]
could we simply include the keys with the right trust level in the DTS image at build time?

**Comment by macpijan** [comment]
> could we simply include the keys with the right trust level in the DTS image at build time?

@mkopec I would prefer that, too.

Do you know how it should be done?

You mean to include both 3mdeb and Dasharo master keys and still run `gpg --import-ownertrust` at runtime, or somehow create the trust DB on the builder, and just include the results into the target system?

**Comment by macpijan** [comment]
> We could prepare an Yocto recipe that installs public keys from https://github.com/3mdeb/3mdeb-secpack/

Yes, at least master keys.

**Comment by pietrushnic** [comment]
This is state-of-the-art. Ownertrust is a plain text document. The Qubes OS community resolved the same issue, but the typical configuration consists of a separate queue of keeping the keys, that's why it is a little bit different situation:
https://github.com/ben-grande/qusal/blob/main/salt/qubes-builder/configure.sls#L61

**Comment by mkopec** [comment]
I was thinking something like this:
- Include 3mdeb master key and latest keys in DTS (preconfigured GPG keyring, or import at boot)
- Set 3mdeb key at ultimate trust level
- Download and import latest Dasharo keys before updating firmware

**Comment by macpijan** [comment]
@pietrushnic 

> Ownertrust is a plain text document.

It is, but is only some intermediate file AFAIK. We already do the same here:  https://github.com/Dasharo/meta-dts/pull/69/files#diff-83430a524e32e99ff8921d9df707448a35c7657511ebfe205f631911ab9c4ac1R713

The trustdb and pubkring files are binary files, that we need to create and install to the target image.

**Comment by mkopec** [comment]
To prepare the keyring at build-time:

```
gpg --no-default-keyring --keyring dts.gpg --homedir dtskeys --recv-keys 1B5785C2965D84CF85D1652B4AFD81D97BD37C54 # can also wget + import
gpg --no-default-keyring --keyring dts.gpg --homedir dtskeys --import-ownertrust <(echo "1B5785C2965D84CF85D1652B4AFD81D97BD37C54:6:")
```

now just include `dtskeys/dts.gpg` and `dtskeys/trustdb.gpg` in the dts image.

in dts, at uptade time get the dasharo release key:

```
$ gpg --no-default-keyring --keyring dts.gpg --homedir gpgtestdir --list-keys
$ wget https://raw.githubusercontent.com/3mdeb/3mdeb-secpack/master/dasharo/3mdeb-dasharo-master-key.asc
$ gpg --no-default-keyring --keyring dts.gpg --homedir gpgtestdir --import 3mdeb-dasharo-master-key.asc
```

and we can see that the imported key is trusted:

```
gpg --no-default-keyring --keyring dts.gpg --homedir gpgtestdir --list-keys
gpg: WARNING: unsafe permissions on homedir '/home/michal/gpgtestdir'
/home/michal/gpgtestdir/dts.gpg
-------------------------------
pub   rsa4096 2019-02-12 [SC]
      1B5785C2965D84CF85D1652B4AFD81D97BD37C54
uid           [ultimate] 3mdeb Master Key <contact@3mdeb.com>

pub   rsa4096 2021-02-03 [SC] [expires: 2026-02-02]
      0D5F6F1DA800329EB7C597A2ABE1D0BC66278008
uid           [  full  ] 3mdeb Dasharo Master Key
sub   rsa4096 2021-02-03 [E] [expires: 2026-02-02]
```

**Comment by TomaszAIR** [comment]
We can also create and install gpg.conf plain text file with list of trusted keys, then trustdb will be created at runtime.

```
root@DasharoToolsSuite:~# vim test/gpg.conf
root@DasharoToolsSuite:~# cat test/gpg.conf 
trusted-key 0x0D5F6F1DA800329EB7C597A2ABE1D0BC66278008
root@DasharoToolsSuite:~# gpg --homedir /home/root/test/ --list-keys
gpg: key ABE1D0BC66278008 marked as ultimately trusted
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: next trustdb check due at 2026-02-02
/home/root/test/pubring.kbx
---------------------------
pub   rsa4096 2021-02-03 [SC] [expires: 2026-02-02]
      0D5F6F1DA800329EB7C597A2ABE1D0BC66278008
uid           [ultimate] 3mdeb Dasharo Master Key
sub   rsa4096 2021-02-03 [E] [expires: 2026-02-02]
```

But I am not sure if there is any difference security-wise in those two solutions

**Comment by pietrushnic** [comment]
@marmarek do you have any opinion here? Maybe we should give a switch in the menu that will give the ability to install keys and trust those; advanced users can compare fingerprints during the process. Or we can just let people know in the documentation that the given list of keys is considered trust: ultimate.

**Comment by macpijan** [comment]
For the upcoming DTS release, we plan to include keyring with 3mdeb and Dasharo master keys trusted as `ultimate`. We will download the release keys at runtime, as we already do. @TomaszAIR will handle that, so we can test this out tomorrow.

**Comment by marmarek** [comment]
IMO at least the master key should be included at build time and trusted (if setting trust at build time is tricky, then doing it at build time is okay, but still keep the fingerprint hardcoded for that). Individual release keys probably better to fetch at runtime as those may depend on which hardware is used.

**Comment by TomaszAIR** [comment]
> For the upcoming DTS release, we plan to include keyring with 3mdeb and Dasharo master keys trusted as ultimate. 

The implementation for that is in https://github.com/Dasharo/meta-dts/pull/71

**Comment by TomaszAIR** [comment]
We end up with adding keyring to the image, it was released in v1.2.14 https://github.com/Dasharo/meta-dts/releases/tag/v1.2.14.

I will close this PR.

btw @miczyg1 thanks for finding this typo https://github.com/Dasharo/meta-dts/pull/69/commits/7d16570784377037ebff75dec3e98b3eb34817da ; added in https://github.com/Dasharo/meta-dts/pull/75/commits

**Pull request closed without merging**
