### PR TITLE
dts-functions.sh: start adding ode to handle seabios builds

### PR DESCRIPTION
**Pull request by pietrushnic**

### CODE REVIEW

**Comment by miczyg1** [comment]
Typo in the commit message? 

start adding **c**ode to handle seabios builds?

**Comment by pietrushnic** [comment]
@miczyg1, I will definitely fix it with another round of code improvements. I would rather look for direction regarding implementation.

**Comment by miczyg1** [comment]
Not sure if this is good direction, but all I can say is to look at:

https://github.com/Dasharo/meta-dts/pull/95/files
https://github.com/Dasharo/meta-dts/pull/104/files
https://github.com/Dasharo/meta-dts/pull/105/files

Adding yet another flavor to the pool will not be trivial with all the autodetection, switching, etc.

**Comment by pietrushnic** [comment]
@miczyg1 we must improve the situation step by step; this code is at the heart of our business model. @macpijan, your support would be appreciated. Maybe @artur-rs can help in improving overall business operations. In my opinion, adding new products to the Dasharo pool takes way too long, and the complexity of scripts makes it very fragile. There is no way we will stop adding products and extending our offering, so the code has to be improved, or we have to redesign things.

**Comment by pietrushnic** [comment]
@miczyg1 I would say it was addressed by @macpijan in 1.2.23

**Pull request closed without merging**
