### PR TITLE
dts-scripts: Enhance verbose mode + collect cbmem console in hcl report

### PR DESCRIPTION
**Pull request by PLangowski**

### CODE REVIEW

**Comment by artur-rs** [comment]
@PLangowski `main` or `develop`? Which version/changelog will include these changes (verbose + cbmem)?

**Comment by PLangowski** [comment]
@artur-rs my bad, it's supposed to be develop

**Review by m-iwanicki — APPROVED** [review]

**Comment by artur-rs** [comment]
@PLangowski waiting for the answer on:
> Which version/changelog will include these changes (verbose + cbmem)?

**Comment by PLangowski** [comment]
@artur-rs I don't know, I guess the next release will include these.

**Comment by PLangowski** [comment]
@artur-rs We can release it as `2.0.1`

**Comment by artur-rs** [comment]
@PLangowski I'm merging this, and the changelog/release info should be added directly on `develop` branch

**Pull request merged**
