### PR TITLE
WIP: Add lshw

### PR DESCRIPTION
**Pull request by pietrushnic**

### CODE REVIEW

**Comment by macpijan** [comment]
@pietrushnic This LGTM, do you need anything else here?

**Comment by pietrushnic** [comment]
@macpijan here, no, but there are definitely other tools missing, which are present e.g. in meta-rte. What should I do with those?

**Comment by macpijan** [comment]
What tools from RTE are missing here?
Aren't you mixing stuff up? If tool was on RTE, it probably was meant to be executed on RTE, not on the platform. Such as WoL, for instance.

**Comment by pietrushnic** [comment]
@macpijan Yes, I'm confusing things. I meant things missing in the DTS vs Debian NFS filesystem. What is definitely missing:
- roca-detect - this is what I'm working on now,

Other issues I face are:
- another thing is an invalid option in `tpm2_changeauth`:
```
tpm2_changeauth: invalid option -- 'o'
```

- and some incompatible output for legacy TPM1.7 test:
```bash
Resolving variable '${list1[1]}' failed: IndexError: list index out of range
```

I probably have to align for the correct output parsing or change things regarding the parameters used.

**Comment by m-iwanicki** [comment]
lshw was added in release v1.2.22 https://github.com/Dasharo/meta-dts/blob/main/CHANGELOG.md#v1222---2024-06-27

**Pull request closed without merging**
