### PR TITLE
Move recipes

### PR DESCRIPTION
**Pull request by Al-an-21**
Recipes that have been moved to:

+ meta-dasharo:

- dasharo-configuration-utility
- dasharo-ectool
- flashrom
- fwupd - fwupd & fwupd-efi inside
- txe-secure-boot 

+ meta-coreboot:

coreboot-utils:
-  cbfstool
- cmem
- ectool
- futil
- ifdtool
- intelmetool
- intelp2m
- inteltool
- msrtool
- nvramtool
- superiotool
- smmstoretool

packagegroups:
- packagegroup-coreboot-utils

### CODE REVIEW

**Comment by m-iwanicki** [comment]
@Al-an-21 this PR should probably be converted to draft PR as it doesn't look ready for review

**Comment by artur-rs** [comment]
@Al-an-21 Also, a merge conflict occurred; please resolve that before requesting a review.

**Comment by m-iwanicki** [comment]
@Al-an-21 you removed a lot of recipes but you don't install them.
You should probably include `meta-dasharo`. Not only that but please at least check if after your changes image can be built:

```
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'txesbmantool' (but /repo/meta-dts-distro/recipes-dts/packagegroups/packagegroup-dts.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'txesbmantool' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['txesbmantool']
NOTE: Runtime target 'packagegroup-dts-python' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-dts-python', 'txesbmantool']
ERROR: Required build target 'dts-base-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['dts-base-image', 'packagegroup-dts-python', 'txesbmantool']

Summary: There was 1 WARNING message.
Summary: There were 2 ERROR messages, returning a non-zero exit code.
2024-11-22 12:08:35 - ERROR    - Command returned non-zero exit status 1
```

**Review by m-iwanicki — CHANGES_REQUESTED** [review]
previous comment

**Review by macpijan — APPROVED** [review]

**Pull request merged**
